#!/bin/bash

source ~/cronwrapper_S3
export PYTHONPATH="${HOME}/git/neoexchange"
logroot=/data/eng/rocks
log=${logroot}/Logs/download_archive_$(date +%F).log

date_options=""
if [[ $# -eq 1 ]]; then
  date=$1
  if [[ ${#date} -eq 8 ]]; then 
    date_options="--date ${date}"
    year=${date:0:4}
    month=${date:4:2}
    day=${date:6:2}
    log=${logroot}/Logs/download_archive_${year}-${month}-${day}.log
    echo "Processing with ${date_options}" >> ${log}
  else
    echo "Incorrect date format; need YYYYMMDD"
  fi
fi
#echo ${log}
touch ${log}
echo "================= $(date +"%F %T %Z") =================" >> ${log}

cd $PYTHONPATH/neoexchange
python3 manage.py download_archive_data --datadir ${logroot} ${date_options} --spectraonly >> ${log} 2>&1
#python3 manage.py download_archive_data --datadir ${logroot} ${date_options} --proposal LCO2020A-011 >> ${log} 2>&1
#python3 manage.py download_archive_data --datadir ${logroot} ${date_options} --proposal LCO2019B-023-TC >> ${log} 2>&1

