# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160822_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='frame',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'FITS filename'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frametype',
            field=models.SmallIntegerField(choices=[(0, b'Single frame'), (1, b'Stack of frames'), (2, b'Non-LCOGT data'), (3, b'Satellite data'), (4, b'Spectrum'), (5, b'FITS LDAC catalog'), (6, b'BANZAI LDAC catalog'), (10, b'ORACDR QL frame'), (11, b'BANZAI QL frame'), (90, b'ORACDR reduced frame'), (91, b'BANZAI reduced frame')], default=0, verbose_name=b'Frame Type'),
        ),
    ]
