# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20161114_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='astrometric_catalog',
            field=models.CharField(default=b' ', max_length=40, verbose_name=b'Astrometric catalog used'),
        ),
        migrations.AddField(
            model_name='frame',
            name='photometric_catalog',
            field=models.CharField(default=b' ', max_length=40, verbose_name=b'Photometric catalog used'),
        ),
    ]
