# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20161117_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemeasurement',
            name='obs_dec',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Observed Dec'),
        ),
        migrations.AlterField(
            model_name='sourcemeasurement',
            name='obs_ra',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Observed RA'),
        ),
    ]
