# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170104_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frameid',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Archive ID'),
        ),
    ]
