# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_frame_frameid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoptesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_submitted', models.DateTimeField(verbose_name=b'Date sent to Zooniverse')),
                ('last_check', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('subject_id', models.IntegerField(verbose_name=b'Subject ID')),
                ('quad', models.IntegerField(verbose_name=b'Quadrant of image')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Block')),
            ],
            options={
                'verbose_name': 'Zooniverse Report',
            },
        ),
    ]
