# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_frame_frameid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoptesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_submitted', models.DateTimeField(blank=True, null=True, verbose_name=b'Date sent to Zooniverse')),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('subject_id', models.IntegerField(blank=True, null=True, verbose_name=b'Subject ID')),
                ('verifications', models.IntegerField(default=0)),
                ('classifiers', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Block')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
            ],
            options={
                'verbose_name': 'Zooniverse Report',
            },
        ),
    ]
