# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_panoptesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoptesreport',
            name='classifiers',
            field=models.TextField(blank=True, help_text=b'Volunteers usernames who found NEOs', null=True),
        ),
    ]
