# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-09 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170807_2019_squashed_0030_auto_20170927_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomic_class', models.CharField(blank=True, max_length=6, null=True, verbose_name=b'Taxonomic Class')),
                ('tax_scheme', models.CharField(blank=True, choices=[(b'T', b'Tholen'), (b'Ba', b'Barucci'), (b'Td', b'Tedesco'), (b'H', b'Howell'), (b'S', b'SMASS'), (b'B', b'Bus'), (b'3T', b'S3OS2_TH'), (b'3B', b'S3OS2_BB'), (b'BD', b'Bus-DeMeo')], max_length=2, null=True, verbose_name=b'Taxonomic Scheme')),
                ('tax_reference', models.CharField(blank=True, choices=[(b'PDS6', b'Neese, C., Ed., Asteroid Taxonomy V6.0. EAR-A-5-DDR-TAXONOMY-V6.0. NASA Planetary Data System, 2010.')], max_length=6, null=True, verbose_name=b'Reference source for Taxonomic data')),
                ('tax_notes', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Notes on Taxonomic Classification')),
            ],
            options={
                'db_table': 'ingest_taxonomy',
                'verbose_name': 'Spectroscopy Detail',
                'verbose_name_plural': 'Spectroscopy Details',
            },
        ),
        migrations.AlterField(
            model_name='body',
            name='origin',
            field=models.CharField(blank=True, choices=[(b'M', b'Minor Planet Center'), (b'N', b'NASA'), (b'S', b'Spaceguard'), (b'D', b'NEODSYS'), (b'G', b'Goldstone'), (b'A', b'Arecibo'), (b'R', b'Goldstone & Arecibo'), (b'L', b'LCOGT'), (b'Y', b'Yarkovsky')], default=b'M', max_length=1, null=True, verbose_name=b'Where did this target come from?'),
        ),
        migrations.AddField(
            model_name='spectralinfo',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Body'),
        ),
    ]
