# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170807_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='superblock',
            name='rapid_response',
            field=models.BooleanField(default=False, verbose_name=b'Is this a ToO/Rapid Response observation?'),
        ),
        migrations.AlterField(
            model_name='body',
            name='origin',
            field=models.CharField(blank=True, choices=[(b'M', b'Minor Planet Center'), (b'N', b'NASA ARM'), (b'S', b'Spaceguard'), (b'D', b'NEODSYS'), (b'G', b'Goldstone'), (b'A', b'Arecibo'), (b'R', b'Goldstone & Arecibo'), (b'L', b'LCOGT'), (b'Y', b'Yarkovsky')], default=b'M', max_length=1, null=True, verbose_name=b'Where did this target come from?'),
        ),
    ]
