# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20171109_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralinfo',
            name='tax_reference',
            field=models.CharField(blank=True, choices=[(b'PDS6', b'Neese, C., Ed., Asteroid Taxonomy V6.0. EAR-A-5-DDR-TAXONOMY-V6.0. NASA Planetary Data System, 2010.'), (b'BZ04', b'Binzel, R. P., Rivkin, A. S., Stuart, J. S., Harris, A. W., Bus, S. J., and Burbine, T. H. (2004).')], max_length=6, null=True, verbose_name=b'Reference source for Taxonomic data'),
        ),
    ]
