# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_previousspectra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousspectra',
            name='spec_ir',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=b'IR Spectra Link'),
        ),
        migrations.AlterField(
            model_name='previousspectra',
            name='spec_source',
            field=models.CharField(blank=True, choices=[(b'S', b'SMASS'), (b'M', b'MANOS'), (b'U', b'Unknown'), (b'O', b'Other')], max_length=1, null=True, verbose_name=b'Source'),
        ),
        migrations.AlterField(
            model_name='previousspectra',
            name='spec_vis',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Visible Spectra Link'),
        ),
        migrations.AlterField(
            model_name='previousspectra',
            name='spec_wav',
            field=models.CharField(blank=True, choices=[(b'Vis', b'Visible'), (b'NIR', b'Near Infrared'), (b'Vis+NIR', b'Both Visible and Near IR'), (b'NA', b'None Yet.')], max_length=7, null=True, verbose_name=b'Wavelength'),
        ),
    ]
