# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20180108_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='source_type',
            field=models.CharField(blank=True, choices=[(b'N', b'NEO'), (b'A', b'Asteroid'), (b'C', b'Comet'), (b'K', b'KBO'), (b'E', b'Centaur'), (b'T', b'Trojan'), (b'U', b'Candidate'), (b'X', b'Did not exist'), (b'W', b'Was not interesting'), (b'D', b'Discovery, non NEO'), (b'J', b'Artificial satellite'), (b'H', b'Hyperbolic asteroids')], max_length=1, null=True, verbose_name=b'Type of object'),
        ),
        migrations.AlterField(
            model_name='spectralinfo',
            name='tax_notes',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Notes on Taxonomic Classification'),
        ),
    ]
