# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180316_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='obstype',
            field=models.SmallIntegerField(choices=[(0, b'Optical imaging'), (1, b'Optical spectra')], default=0, verbose_name=b'Observation Type'),
        ),
    ]
