# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20180414_0054'),
        ('core', '0034_auto_20180316_2235'),
    ]

    operations = [
    ]
