# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180316_2235'),
        ('core', '0034_auto_20171221_2337'),
    ]

    operations = [
    ]
