# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20180606_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='obstype',
            field=models.SmallIntegerField(choices=[(0, 'Optical imaging'), (1, 'Optical spectra')], default=0, verbose_name='Observation Type'),
        ),
    ]
