# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_staticsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='calibsource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.StaticSource'),
        ),
        migrations.AlterField(
            model_name='block',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Body'),
        ),
    ]
