# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20180709_2022_squashed_0041_auto_20180711_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='superblock',
            name='calibsource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.StaticSource'),
        ),
        migrations.AlterField(
            model_name='superblock',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Body'),
        ),
    ]
