# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20180724_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='midpoint',
            field=models.DateTimeField(db_index=True, verbose_name='UTC date/time of frame midpoint'),
        ),
    ]
