# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20181105_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='site',
            field=models.CharField(choices=[('ogg', 'Haleakala'), ('coj', 'Siding Spring'), ('lsc', 'Cerro Tololo'), ('elp', 'McDonald'), ('cpt', 'Sutherland'), ('tfn', 'Tenerife'), ('sbg', 'SBIG cameras'), ('sin', 'Sinistro cameras'), ('spc', 'Spectral cameras')], max_length=3, null=True),
        ),
    ]
