# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20181116_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='orbit_rms',
            field=models.FloatField(blank=True, null=True, verbose_name='Orbit quality of fit'),
        ),
        migrations.AlterField(
            model_name='spectralinfo',
            name='tax_reference',
            field=models.CharField(blank=True, choices=[('PDS6', 'Neese, Asteroid Taxonomy V6.0, (2010).'), ('BZ04', 'Binzel, et al. (2004).'), ('SDSS', 'Hasselmann, et al. Asteroid Taxonomy V1.1, (2012).')], max_length=6, null=True, verbose_name='Reference source for Taxonomic data'),
        ),
        migrations.AlterField(
            model_name='spectralinfo',
            name='tax_scheme',
            field=models.CharField(blank=True, choices=[('T', 'Tholen'), ('Ba', 'Barucci'), ('Td', 'Tedesco'), ('H', 'Howell'), ('S', 'SMASS'), ('B', 'Bus'), ('3T', 'S3OS2_TH'), ('3B', 'S3OS2_BB'), ('BD', 'Bus-DeMeo'), ('Sd', 'SDSS')], max_length=2, null=True, verbose_name='Taxonomic Scheme'),
        ),
    ]
