# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20190304_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='download',
            field=models.BooleanField(default=True, verbose_name='Auto download data?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='time_critical',
            field=models.BooleanField(default=False, verbose_name='Time Critical/ToO proposal?'),
        ),
    ]
