# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20190301_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='orbit_rms',
            field=models.FloatField(blank=True, default=99.0, null=True, verbose_name='Orbit quality of fit'),
        ),
    ]
