# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190613_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='source_subtype_1',
            field=models.CharField(blank=True, choices=[('N', 'NEO'), ('N1', 'Atira'), ('N2', 'Aten'), ('N3', 'Apollo'), ('N4', 'Amor'), ('PH', 'PHA'), ('MI', 'Inner Main-Belt'), ('M', 'Main-Belt'), ('MO', 'Outer Main-Belt'), ('A', 'Active'), ('MH', 'Hilda'), ('T4', 'L4'), ('T5', 'L5'), ('P1', 'Mercury'), ('P2', 'Venus'), ('P3', 'Earth'), ('P4', 'Mars'), ('P5', 'Jupiter'), ('P6', 'Saturn'), ('P7', 'Uranus'), ('P8', 'Neptune'), ('P9', 'Pluto'), ('PL', 'Plutino'), ('K', 'Classical KBO'), ('S', 'SDO'), ('H', 'Hyperbolic'), ('PA', 'Parabolic'), ('JF', 'Jupiter Family'), ('HT', 'Halley-Type')], max_length=2, null=True, verbose_name='Subtype of object'),
        ),
        migrations.AddField(
            model_name='body',
            name='source_subtype_2',
            field=models.CharField(blank=True, choices=[('N', 'NEO'), ('N1', 'Atira'), ('N2', 'Aten'), ('N3', 'Apollo'), ('N4', 'Amor'), ('PH', 'PHA'), ('MI', 'Inner Main-Belt'), ('M', 'Main-Belt'), ('MO', 'Outer Main-Belt'), ('A', 'Active'), ('MH', 'Hilda'), ('T4', 'L4'), ('T5', 'L5'), ('P1', 'Mercury'), ('P2', 'Venus'), ('P3', 'Earth'), ('P4', 'Mars'), ('P5', 'Jupiter'), ('P6', 'Saturn'), ('P7', 'Uranus'), ('P8', 'Neptune'), ('P9', 'Pluto'), ('PL', 'Plutino'), ('K', 'Classical KBO'), ('S', 'SDO'), ('H', 'Hyperbolic'), ('PA', 'Parabolic'), ('JF', 'Jupiter Family'), ('HT', 'Halley-Type')], max_length=2, null=True, verbose_name='Subtype of object'),
        ),
        migrations.AlterField(
            model_name='body',
            name='source_type',
            field=models.CharField(blank=True, choices=[('N', 'NEO'), ('A', 'Asteroid'), ('C', 'Comet'), ('K', 'TNO'), ('E', 'Centaur'), ('T', 'Trojan'), ('U', 'Candidate'), ('X', 'Did not exist'), ('W', 'Was not interesting'), ('D', 'Discovery, non NEO'), ('J', 'Artificial satellite'), ('M', 'Natural Satellite'), ('P', 'Major Planet')], max_length=1, null=True, verbose_name='Type of object'),
        ),
    ]
