# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190710_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig', models.CharField(blank=True, max_length=30, null=True, verbose_name='Designation')),
                ('desig_type', models.CharField(blank=True, choices=[('N', 'Name'), ('#', 'Number'), ('P', 'Provisional Designation'), ('C', 'NEO Candidate Designation'), ('T', 'Temporary Designation')], max_length=1, null=True, verbose_name='Designation Type')),
                ('preferred', models.BooleanField(default=False, verbose_name='Is this the preferred designation of this type?')),
                ('packed', models.BooleanField(default=False, verbose_name='Is this a packed designation?')),
                ('desig_notes', models.CharField(blank=True, max_length=30, null=True, verbose_name='Notes on Nomenclature')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Body')),
            ],
            options={
                'verbose_name': 'Object Designation',
                'verbose_name_plural': 'Object Designations',
                'db_table': 'ingest_names',
            },
        ),
    ]
