# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_designations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_band', models.CharField(blank=True, max_length=30, null=True, verbose_name='X-X filter combination')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Color Value')),
                ('error', models.FloatField(blank=True, null=True, verbose_name='Color error')),
                ('units', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color Units')),
                ('quality', models.CharField(blank=True, max_length=10, null=True, verbose_name='Color Quality Designation')),
                ('preferred', models.BooleanField(default=False, verbose_name='Is this the preferred value for this color band?')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference for this value')),
                ('notes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Notes on this value')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Body')),
            ],
            options={
                'verbose_name': 'Color Value',
                'verbose_name_plural': 'Color Values',
                'db_table': 'ingest_colors',
            },
        ),
        migrations.CreateModel(
            name='PhysicalParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(blank=True, choices=[('H', 'Absolute Magnitude'), ('G', 'Phase Slope'), ('D', 'Diameter'), ('R', 'Density'), ('P', 'Rotation Period'), ('A', 'LC Amplitude'), ('O', 'Pole Orientation'), ('ab', 'Albedo'), ('Y', 'Yarkovsky Drift'), ('E', 'Coma Extent')], max_length=2, null=True, verbose_name='Physical Parameter Type')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Physical Parameter Value')),
                ('error', models.FloatField(blank=True, null=True, verbose_name='Physical Parameter Error')),
                ('value2', models.FloatField(blank=True, null=True, verbose_name='2nd component of Physical Parameter')),
                ('error2', models.FloatField(blank=True, null=True, verbose_name='Error for 2nd component of Physical Parameter')),
                ('units', models.CharField(blank=True, max_length=30, null=True, verbose_name='Physical Parameter Units')),
                ('quality', models.CharField(blank=True, max_length=10, null=True, verbose_name='Physical Parameter Quality Designation')),
                ('preferred', models.BooleanField(default=False, verbose_name='Is this the preferred value for this type of parameter?')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference for this value')),
                ('notes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Notes on this value')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Body')),
            ],
            options={
                'verbose_name': 'Physical Parameter',
                'verbose_name_plural': 'Physical Parameters',
                'db_table': 'ingest_physical_parameters',
            },
        ),
    ]
