# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-13 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20191112_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvalues',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designations',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalparameters',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
