# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-07 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20191113_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsources',
            name='obs_dec',
            field=models.FloatField(db_index=True, verbose_name='Observed Dec'),
        ),
        migrations.AlterField(
            model_name='catalogsources',
            name='obs_ra',
            field=models.FloatField(db_index=True, verbose_name='Observed RA'),
        ),
        migrations.AlterField(
            model_name='catalogsources',
            name='obs_x',
            field=models.FloatField(db_index=True, verbose_name='CCD X co-ordinate'),
        ),
        migrations.AlterField(
            model_name='catalogsources',
            name='obs_y',
            field=models.FloatField(db_index=True, verbose_name='CCD Y co-ordinate'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='filename',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='FITS filename'),
        ),
    ]
