# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20191113_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='request_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='body',
            name='ingest',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='body',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='body',
            name='provisional_name',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Provisional MPC designation'),
        ),
        migrations.AlterField(
            model_name='body',
            name='provisional_packed',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name='MPC name in packed format'),
        ),
        migrations.AlterField(
            model_name='body',
            name='update_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='avg_midpoint',
            field=models.DateTimeField(db_index=True, verbose_name='Average UTC midpoint'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='score',
            field=models.FloatField(db_index=True, verbose_name='Candidate Score'),
        ),
        migrations.AlterField(
            model_name='catalogsources',
            name='obs_dec',
            field=models.FloatField(db_index=True, verbose_name='Observed Dec'),
        ),
        migrations.AlterField(
            model_name='catalogsources',
            name='obs_ra',
            field=models.FloatField(db_index=True, verbose_name='Observed RA'),
        ),
        migrations.AlterField(
            model_name='catalogsources',
            name='obs_x',
            field=models.FloatField(db_index=True, verbose_name='CCD X co-ordinate'),
        ),
        migrations.AlterField(
            model_name='catalogsources',
            name='obs_y',
            field=models.FloatField(db_index=True, verbose_name='CCD Y co-ordinate'),
        ),
        migrations.AlterField(
            model_name='colorvalues',
            name='update_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='colorvalues',
            name='value',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Color Value'),
        ),
        migrations.AlterField(
            model_name='designations',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='filename',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='FITS filename'),
        ),
        migrations.AlterField(
            model_name='physicalparameters',
            name='update_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalparameters',
            name='value',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Physical Parameter Value'),
        ),
        migrations.AlterField(
            model_name='sourcemeasurement',
            name='obs_dec',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Observed Dec'),
        ),
        migrations.AlterField(
            model_name='sourcemeasurement',
            name='obs_mag',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Observed Magnitude'),
        ),
        migrations.AlterField(
            model_name='sourcemeasurement',
            name='obs_ra',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Observed RA'),
        ),
        migrations.AlterField(
            model_name='staticsource',
            name='dec',
            field=models.FloatField(db_index=True, verbose_name='Dec of source (degrees)'),
        ),
        migrations.AlterField(
            model_name='staticsource',
            name='name',
            field=models.CharField(db_index=True, max_length=55, verbose_name='Name of calibration source'),
        ),
        migrations.AlterField(
            model_name='staticsource',
            name='ra',
            field=models.FloatField(db_index=True, verbose_name='RA of source (degrees)'),
        ),
        migrations.AlterField(
            model_name='superblock',
            name='block_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='superblock',
            name='block_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='superblock',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
