# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-24 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200128_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panoptesreport',
            name='block',
        ),
        migrations.RemoveField(
            model_name='panoptesreport',
            name='candidate',
        ),
        migrations.AlterField(
            model_name='body',
            name='ingest',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 2, 24, 9, 36, 26, 936872)),
        ),
        migrations.DeleteModel(
            name='PanoptesReport',
        ),
    ]
