# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-25 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200224_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='ingest',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.utcnow),
        ),
    ]
