# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20200225_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='origin',
            field=models.CharField(blank=True, choices=[('M', 'Minor Planet Center'), ('N', 'NASA'), ('S', 'Spaceguard'), ('D', 'NEODSYS'), ('G', 'Goldstone'), ('A', 'Arecibo'), ('R', 'Goldstone & Arecibo'), ('L', 'LCOGT'), ('Y', 'Yarkovsky'), ('T', 'Trojan'), ('O', 'LOOK Project')], default='M', max_length=1, null=True, verbose_name='Where did this target come from?'),
        ),
        migrations.AlterField(
            model_name='body',
            name='source_subtype_1',
            field=models.CharField(blank=True, choices=[('N', 'NEO'), ('N1', 'Atira'), ('N2', 'Aten'), ('N3', 'Apollo'), ('N4', 'Amor'), ('PH', 'PHA'), ('MI', 'Inner Main-Belt'), ('M', 'Main-Belt'), ('MO', 'Outer Main-Belt'), ('A', 'Active'), ('MH', 'Hilda'), ('T4', 'L4'), ('T5', 'L5'), ('P1', 'Mercury'), ('P2', 'Venus'), ('P3', 'Earth'), ('P4', 'Mars'), ('P5', 'Jupiter'), ('P6', 'Saturn'), ('P7', 'Uranus'), ('P8', 'Neptune'), ('P9', 'Pluto'), ('PL', 'Plutino'), ('K', 'Classical KBO'), ('S', 'SDO'), ('H', 'Hyperbolic'), ('PA', 'Parabolic'), ('JF', 'Jupiter Family'), ('HT', 'Halley-Type'), ('LP', 'Long Period')], max_length=2, null=True, verbose_name='Subtype of object'),
        ),
        migrations.AlterField(
            model_name='body',
            name='source_subtype_2',
            field=models.CharField(blank=True, choices=[('N', 'NEO'), ('N1', 'Atira'), ('N2', 'Aten'), ('N3', 'Apollo'), ('N4', 'Amor'), ('PH', 'PHA'), ('MI', 'Inner Main-Belt'), ('M', 'Main-Belt'), ('MO', 'Outer Main-Belt'), ('A', 'Active'), ('MH', 'Hilda'), ('T4', 'L4'), ('T5', 'L5'), ('P1', 'Mercury'), ('P2', 'Venus'), ('P3', 'Earth'), ('P4', 'Mars'), ('P5', 'Jupiter'), ('P6', 'Saturn'), ('P7', 'Uranus'), ('P8', 'Neptune'), ('P9', 'Pluto'), ('PL', 'Plutino'), ('K', 'Classical KBO'), ('S', 'SDO'), ('H', 'Hyperbolic'), ('PA', 'Parabolic'), ('JF', 'Jupiter Family'), ('HT', 'Halley-Type'), ('LP', 'Long Period')], max_length=2, null=True, verbose_name='Subtype of object'),
        ),
    ]
