# Generated by Django 3.1.3 on 2020-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200701_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalparameters',
            name='parameter_type',
            field=models.CharField(blank=True, choices=[('H', 'Absolute Magnitude'), ('G', 'Phase Slope'), ('D', 'Diameter'), ('R', 'Density'), ('P', 'Rotation Period'), ('A', 'LC Amplitude'), ('O', 'Pole Orientation'), ('ab', 'Albedo'), ('Y', 'Yarkovsky Drift'), ('E', 'Coma Extent'), ('M', 'Mass'), ('/a', 'Reciprocal of semimajor axis')], max_length=2, null=True, verbose_name='Physical Parameter Type'),
        ),
    ]
