# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200701_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('terminal_timestamp', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='physicalparameters',
            name='parameter_type',
            field=models.CharField(blank=True, choices=[('H', 'Absolute Magnitude'), ('G', 'Phase Slope'), ('D', 'Diameter'), ('R', 'Density'), ('P', 'Rotation Period'), ('A', 'LC Amplitude'), ('O', 'Pole Orientation'), ('ab', 'Albedo'), ('Y', 'Yarkovsky Drift'), ('E', 'Coma Extent'), ('M', 'Mass'), ('/a', 'Reciprocal of semimajor axis')], max_length=2, null=True, verbose_name='Physical Parameter Type'),
        ),
        migrations.CreateModel(
            name='PipelineProcess',
            fields=[
                ('asyncprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.AsyncProcess')),
                ('logs', models.TextField(blank=True, null=True)),
                ('inputs_json', models.TextField(blank=True, null=True)),
            ],
            bases=('core.asyncprocess',),
        ),
    ]
