# Generated by Django 3.1.2 on 2020-12-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200909_1600'),
        ('core', '0058_auto_20201119_1751'),
    ]

    operations = [
    ]
