# Generated by Django 3.1.11 on 2021-05-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20201119_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='origin',
            field=models.CharField(blank=True, choices=[('M', 'Minor Planet Center'), ('H', 'JPL HORIZONS'), ('N', 'NASA'), ('S', 'Spaceguard'), ('D', 'NEODSYS'), ('G', 'Goldstone'), ('A', 'Arecibo'), ('R', 'Goldstone & Arecibo'), ('L', 'LCOGT'), ('Y', 'Yarkovsky'), ('T', 'Trojan'), ('O', 'LOOK Project')], default='M', max_length=1, null=True, verbose_name='Where did this target come from?'),
        ),
    ]
