# Generated by Django 3.1.2 on 2021-05-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_dataproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='product',
            field=models.FileField(blank=True, upload_to='products/'),
        ),
    ]
