# Generated by Django 3.1.10 on 2021-08-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_dataproduct_squashed_0061_auto_20210514_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproduct',
            name='update',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='filetype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'JPEG'), (1, 'Spectroscopy Guider GIF'), (22, 'Thumbnail Frame GIF'), (2, 'FITS Image'), (3, 'FITS Spectra'), (4, 'ALCDEF Lightcurve  file'), (5, 'MP4'), (6, 'CSV'), (7, 'PNG astrometric ref stars'), (8, 'PNG photometric ref stars'), (9, 'Block light curve PNG (phased)'), (10, 'Block light curve PNG (unphased)'), (11, 'Combined light curve PNG (phased)'), (12, 'Combined light curve PNG (unphased)'), (13, 'Period finder periodogram PNG'), (14, 'Period finder data window PNG'), (15, 'FWHM condition PNG'), (16, 'Zero point PNG'), (20, 'Planetary Data System (PDS) XML'), (99, 'Other')]),
        ),
    ]
