# Generated by Django 3.1.2 on 2021-05-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20210512_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='filetype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'JPEG'), (1, 'Guider GIF'), (2, 'FITS Image'), (3, 'FITS Spectra'), (4, 'ALCDEF file'), (5, 'MP4'), (6, 'CSV'), (7, 'PNG astrometric ref stars'), (8, 'PNG photometric ref stars'), (9, 'Block light curve PNG (phased)'), (10, 'Block light curve PNG (unphased)'), (11, 'Combined light curve PNG (phased)'), (12, 'Combined light curve PNG (unphased)'), (13, 'Period finder periodogram PNG'), (14, 'Period finder data window PNG'), (15, 'FWHM condition PNG'), (16, 'Zero point PNG'), (20, 'Planetary Data System (PDS) XML'), (99, 'Other')]),
        ),
    ]
