# Generated by Django 3.1.13 on 2021-12-22 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0061_auto_20211208_2330'), ('core', '0062_auto_20211214_2332'), ('core', '0063_auto_20211214_2345'), ('core', '0064_auto_20211218_0114')]

    dependencies = [
        ('core', '0060_auto_20210820_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='as_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Datetime of the products creation or most recent update.'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='filetype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'JPEG'), (1, 'Spectroscopy Guider GIF'), (22, 'Thumbnail Frame GIF'), (2, 'FITS Image'), (3, 'FITS Spectra'), (4, 'ALCDEF Lightcurve file'), (23, 'Periodogram output file'), (24, 'Model Lightcurve output file'), (25, 'Parameter file used to create DAMIT lightcurve models'), (26, 'Shape Model output file'), (5, 'MP4'), (6, 'CSV'), (7, 'PNG astrometric ref stars'), (8, 'PNG photometric ref stars'), (9, 'Block light curve PNG (phased)'), (10, 'Block light curve PNG (unphased)'), (11, 'Combined light curve PNG (phased)'), (12, 'Combined light curve PNG (unphased)'), (13, 'Period finder periodogram PNG'), (14, 'Period finder data window PNG'), (15, 'FWHM condition PNG'), (16, 'Zero point PNG'), (20, 'Planetary Data System (PDS) XML'), (99, 'Other')], verbose_name='Type of file to be stored.'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='product',
            field=models.FileField(blank=True, upload_to='products/', verbose_name='Filefield for actual data product.'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='update',
            field=models.BooleanField(default=True, verbose_name='Flag for allowing automated updates. Set to False for robust storage.'),
        ),
        migrations.AddField(
            model_name='body',
            name='analysis_status',
            field=models.IntegerField(choices=[(0, 'No Analysis Done'), (1, 'Light Curve Analysis Done'), (2, 'Spectroscopic Analysis Done'), (3, 'LC & Spec Analysis Done'), (10, 'More Observations Needed'), (20, 'Published'), (99, 'No usable Data')], db_index=True, default=0, verbose_name='Current Analysis Status'),
        ),
    ]
