# Generated by Django 3.1.13 on 2022-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20211208_2330_squashed_0064_auto_20211218_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalparameters',
            name='quality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Physical Parameter Quality Designation'),
        ),
    ]
