# Generated by Django 3.1.13 on 2022-01-28 22:17
"""
This is a Data Migration to set existing static source blocks to sidereal tracking.
https://docs.djangoproject.com/en/3.1/topics/migrations/#data-migrations
"""

from django.db import migrations


def set_stellar_tracking(apps, schema_editor):
    Block = apps.get_model('core', 'Block')
    for star_block in Block.objects.exclude(calibsource=None):
        star_block.tracking_rate = 0
        star_block.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_block_tracking_rate'),
    ]

    operations = [
        migrations.RunPython(set_stellar_tracking)
    ]
