# Generated by Django 3.1.14 on 2022-06-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20220128_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('terminal_timestamp', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineProcess',
            fields=[
                ('asyncprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.asyncprocess')),
                ('logs', models.TextField(blank=True, null=True)),
                ('inputs_json', models.TextField(blank=True, null=True)),
            ],
            bases=('core.asyncprocess',),
        ),
    ]
