# Generated by Django 3.1.14 on 2022-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_asyncprocess_pipelineprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticsource',
            name='source_type',
            field=models.IntegerField(choices=[(0, 'Unknown source type'), (1, 'Spectrophotometric standard'), (2, 'Radial velocity standard'), (4, 'Solar spectrum standard'), (8, 'Spectral standard'), (16, 'Reference field')], default=0, verbose_name='Source Type'),
        ),
    ]
