# Generated by Django 3.1.14 on 2023-03-06 23:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20221012_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_path', models.CharField(max_length=4096, null=True, verbose_name='Input path to exporter')),
                ('export_path', models.CharField(max_length=4096, null=True, verbose_name='Export path from exporter')),
                ('export_format', models.SmallIntegerField(choices=[(1, 'PDS V4 collection'), (10, 'Tarball of files')], default=1, verbose_name='Export format')),
                ('when_exported', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.block')),
            ],
            options={
                'verbose_name': 'Exported Block',
                'verbose_name_plural': 'Exported Blocks',
            },
        ),
    ]
