# Generated by Django 3.1.14 on 2022-08-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20220801_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frametype',
            field=models.SmallIntegerField(choices=[(0, 'Single frame'), (1, 'Stack of frames'), (2, 'Non-LCOGT data'), (3, 'Satellite data'), (4, 'Spectrum'), (5, 'FITS LDAC catalog'), (6, 'BANZAI LDAC catalog'), (10, 'ORACDR QL frame'), (11, 'BANZAI QL frame'), (80, 'Reference frame'), (90, 'ORACDR reduced frame'), (91, 'BANZAI reduced frame'), (92, 'NEOexchange reduced frame')], default=0, verbose_name='Frame Type'),
        ),
    ]
