# Generated by Django 3.1.14 on 2023-05-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_exportedblock'),
        ('core', '0065_blockobserver'),
    ]

    operations = [
    ]
