# Generated by Django 3.1.14 on 2022-10-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20220802_0607'),
        ('core', '0065_auto_20221012_1840'),
    ]

    operations = [
    ]
