# Generated by Django 3.1.14 on 2023-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_merge_20221012_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemeasurement',
            name='aperture_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Radius of aperture (arcsec)'),
        ),
        migrations.AlterField(
            model_name='sourcemeasurement',
            name='snr',
            field=models.FloatField(blank=True, null=True, verbose_name='Signal to noise ratio'),
        ),
    ]
