# Generated by Django 3.1.14 on 2023-01-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20230127_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='site',
            field=models.CharField(choices=[('ogg', 'Haleakala'), ('coj', 'Siding Spring'), ('lsc', 'Cerro Tololo'), ('elp', 'McDonald'), ('cpt', 'Sutherland'), ('tfn', 'Tenerife'), ('sbg', 'SBIG cameras'), ('sin', 'Sinistro cameras'), ('spc', 'Spectral cameras'), ('lco', 'Las Campanas')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frametype',
            field=models.SmallIntegerField(choices=[(0, 'Single frame'), (1, 'Stack of frames'), (2, 'Non-LCOGT data'), (3, 'Satellite data'), (4, 'Spectrum'), (5, 'FITS LDAC catalog'), (6, 'BANZAI LDAC catalog'), (10, 'ORACDR QL frame'), (11, 'BANZAI QL frame'), (70, 'Swope reduced frame'), (80, 'Reference frame'), (90, 'ORACDR reduced frame'), (91, 'BANZAI reduced frame'), (92, 'NEOexchange reduced frame'), (93, 'NEOexchange DIA subtracted frame')], default=0, verbose_name='Frame Type'),
        ),
    ]
