# Generated by Django 3.1.14 on 2023-03-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20230127_2133'),
        ('core', '0066_exportedblock'),
    ]

    operations = [
    ]
