# Generated by Django 3.1.14 on 2023-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20230916_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='site',
            field=models.CharField(choices=[('ogg', 'Haleakala'), ('coj', 'Siding Spring'), ('lsc', 'Cerro Tololo'), ('elp', 'McDonald'), ('cpt', 'Sutherland'), ('tfn', 'Tenerife'), ('sbg', 'SBIG cameras'), ('sin', 'Sinistro cameras'), ('spc', 'Spectral cameras'), ('lco', 'Las Campanas'), ('mro', 'Magdalena Ridge')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='telclass',
            field=models.CharField(choices=[('1m0', '1-meter'), ('2m0', '2-meter'), ('0m4', '0.4-meter'), ('2m4', '2.4-meter')], default='1m0', max_length=3),
        ),
        migrations.AlterField(
            model_name='superblock',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
