# Generated by Django 3.1.14 on 2023-09-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20230918_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frametype',
            field=models.SmallIntegerField(choices=[(0, 'Single frame'), (1, 'Stack of frames'), (2, 'Non-LCOGT data'), (3, 'Satellite data'), (4, 'Spectrum'), (5, 'FITS LDAC catalog'), (6, 'BANZAI LDAC catalog'), (10, 'ORACDR QL frame'), (11, 'BANZAI QL frame'), (60, 'MRO raw frame'), (61, 'MRO reduced frame'), (70, 'Swope raw frame'), (71, 'Swope reduced frame'), (80, 'Reference frame'), (90, 'ORACDR reduced frame'), (91, 'BANZAI reduced frame'), (92, 'NEOexchange reduced frame'), (93, 'NEOexchange DIA subtracted frame')], default=0, verbose_name='Frame Type'),
        ),
    ]
