# Generated by Django 3.1.14 on 2024-04-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_proposal_code'),
        ('core', '0074_auto_20230918_2304'),
    ]

    operations = [
    ]
