#!/bin/bash

# Turn off core dumps
ulimit -c 0

# Setup locations for AstroPy's config and caches
mkdir -p /var/www/apps/astropyconfig/astropy
mkdir -p /var/www/apps/astropycache/astropy

chmod g+s /data/eng/rocks

# use "/bin/bash" as the default command if none was specified
[[ "$#" -eq "0" ]] && set -- /bin/bash

# execute default command
exec "$@"
