# Generated by Django 3.1.6 on 2021-02-22 06:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OBSERVATION', 'Observations'), ('CAMPAIGN', 'Campaign'), ('DOWNTIME', 'Downtime/unavailability')], help_text='The type of CalEvent', max_length=40)),
                ('start', models.DateTimeField(db_index=True, help_text='The time when this CalEvent starts')),
                ('end', models.DateTimeField(db_index=True, help_text='The time when this CalEvent ends')),
                ('resource', models.CharField(help_text='The telescope or other resource this CalEvent refers to', max_length=255)),
                ('state', models.CharField(choices=[('PROPOSED', 'Proposed or planned'), ('SCHEDULED', 'Time awarded or scheduled'), ('COMPLETED', 'Observed/Completed'), ('FAILED', 'Not obtained (clouded out, etc)'), ('CANCELLED', 'Cancelled')], default='PROPOSED', help_text='Current state of this CalEvent', max_length=40)),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow, help_text='Time when this CalEvent was created')),
                ('modified', models.DateTimeField(blank=True, db_index=True, help_text='Time when this CalEvent was last changed', null=True)),
                ('event_note', models.CharField(blank=True, default='', max_length=255)),
                ('submitter', models.ForeignKey(help_text='The user that submitted this CalEvent', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
