# Generated by Django 3.1.12 on 2021-06-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='event_type',
            field=models.CharField(choices=[('OBSERVATION', 'Observations'), ('NIGHT', 'Night of observations'), ('CAMPAIGN', 'Campaign'), ('DOWNTIME', 'Downtime/unavailability')], help_text='The type of CalEvent', max_length=40),
        ),
    ]
