"""
NEO exchange: NEO observing portal for Las Cumbres Observatory
Copyright (C) 2016-2019 LCO

image_subs.py -- Code to create weight images for SWarp from the rms images generated by SExtractor.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

def boolean_pixel_mask(fits_path):
    #Convert BPM (bad pixel mask)to boolean mask
    return

def generate_weights():
    #rms-ify false values
    return
