#!/bin/bash

# Substitute the prefix into the nginx configuration
echo "Running with PREFIX=${PREFIX}"
sed -i -e "s:@PREFIX@:${PREFIX}:g" /etc/nginx/nginx.conf

# If any schema changed have happened but not been applied
python /var/www/apps/neoexchange/manage.py migrate --noinput

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf