#!/bin/bash

# Substitute the prefix into the nginx configuration
echo "Running with PREFIX=${PREFIX}"
sed -i -e "s:@PREFIX@:${PREFIX}:g" /etc/nginx/nginx.conf

# If any schema changed have happened but not been applied
python /var/www/apps/neoexchange/manage.py migrate --noinput
# Generate cron wrapper to set correct environment variables
cat > /var/www/apps/neoexchange/cronwrapper << EOF
export PYTHONPATH="${PYTHONPATH}"
export DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE}"
export PREFIX="${PREFIX}"

export NEOX_DB_HOST="${NEOX_DB_HOST}"
export NEOX_DB_USER="${NEOX_DB_USER}"
export NEOX_DB_PASSWD="${NEOX_DB_PASSWD}"
export NEOX_OPBEAT_TOKEN="${NEOX_OPBEAT_TOKEN}"
export NEOX_OPBEAT_ORGID="${NEOX_OPBEAT_ORGID}"
export NEOX_OPBEAT_APPID="${NEOX_OPBEAT_APPID}"

EOF

# Make cron wrapper executable
chmod +x /var/www/apps/neoexchange/cronwrapper

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf