#!/bin/bash

# Substitute the prefix into the nginx configuration
echo "Running with PREFIX=${PREFIX}"
sed -i -e "s:@PREFIX@:${PREFIX}:g" /etc/nginx/nginx.conf

# Setup the LCOGT NEOx webapp
python /var/www/apps/neoexchange/manage.py migrate --noinput
python /var/www/apps/neoexchange/manage.py collectstatic --noinput

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
